/**
 * Parity tests for the TypeScript SOP engine (`src/docs/sop/`).
 *
 * The fixtures under `tests/fixtures/` are golden outputs generated by the
 * canonical Python implementation
 * (`lambda-functions/src/lambda_functions/sop_parse.py` and `sop_lint.py`) — see
 * `.tmp/gen_sop_fixtures.py` / `.tmp/gen_sop_synthetic.py` for how they are
 * produced. This suite asserts the TS port yields equivalent structured parse
 * output and identical lint results, both over the real `content/` SOP corpus
 * and over synthetic edge cases that exercise code paths absent from real
 * content (raw procedures, todos, prose, parse errors, every lint violation).
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';
import { readFileSync } from 'node:fs';
import path from 'node:path';

import { ParseError, parse } from '../src/docs/sop/parse';
import { lintText } from '../src/docs/sop/lint';

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const FIXTURES = path.resolve(__dirname, 'fixtures');

interface CorpusCase {
  path: string;
  parse: unknown;
  lint: string[];
}

interface SyntheticCase {
  name: string;
  text: string;
  parse?: unknown;
  parse_error?: string;
  lint: string[];
}

function loadFixture<T>(file: string): { count: number; cases: T[] } {
  return JSON.parse(readFileSync(path.join(FIXTURES, file), 'utf-8'));
}

describe('SOP engine — parity with the Python implementation over content/', () => {
  const fixture = loadFixture<CorpusCase>('sop-parity.json');

  it('has a representative corpus of marked-up SOPs', () => {
    // The full schema_version: 1 corpus is captured; guard against an empty or
    // truncated fixture silently passing.
    assert.ok(fixture.count >= 200, `expected a large corpus, got ${fixture.count}`);
    assert.strictEqual(fixture.cases.length, fixture.count);
  });

  for (const c of fixture.cases) {
    it(`parse + lint parity: ${c.path}`, () => {
      const text = readFileSync(path.join(REPO_ROOT, c.path), 'utf-8');
      const parsed = JSON.parse(JSON.stringify(parse(text)));
      assert.deepStrictEqual(parsed, c.parse, `parse mismatch for ${c.path}`);
      assert.deepStrictEqual(lintText(text), c.lint, `lint mismatch for ${c.path}`);
    });
  }
});

describe('SOP engine — parity on synthetic edge cases', () => {
  const fixture = loadFixture<SyntheticCase>('sop-synthetic.json');

  it('covers raw procedures, todos, prose, errors, and all lint violations', () => {
    assert.ok(fixture.count >= 15, `expected edge-case coverage, got ${fixture.count}`);
  });

  for (const c of fixture.cases) {
    it(`synthetic parity: ${c.name}`, () => {
      if (c.parse_error !== undefined) {
        assert.throws(
          () => parse(c.text),
          (err: unknown) => {
            assert.ok(err instanceof ParseError, 'expected a ParseError');
            assert.strictEqual(err.toString(), c.parse_error);
            return true;
          },
          `expected parse error for ${c.name}`,
        );
      } else {
        const parsed = JSON.parse(JSON.stringify(parse(c.text)));
        assert.deepStrictEqual(parsed, c.parse, `parse mismatch for ${c.name}`);
      }
      assert.deepStrictEqual(lintText(c.text), c.lint, `lint mismatch for ${c.name}`);
    });
  }
});
