import { createHash } from 'crypto';
import ExcelJS from 'exceljs';

export type ImportRow = Record<string, string | number | undefined> & { transactionDate: string; counterparty: string; description: string; amount: string; currency: string; sourceType: string; sourceKey: string; sourceCoordinate?: string };
export type Rejection = { sheet: string; row: number; reason: string };
const headers: Record<string,string> = {
  date:'transactionDate', sent:'transactionDate', 'sent date':'transactionDate', paid:'paidDate', 'paid date':'paidDate',
  provider:'counterparty', payee:'counterparty', name:'counterparty', description:'description', amount:'amount', currency:'currency',
  eur:'amountEur', 'amount eur':'amountEur', statement:'statementRef', reference:'statementRef', count:'quantity', quantity:'quantity',
  comment:'comment', type:'entryType', subtype:'subtype', period:'period', category:'category', tax:'description',
};
const cellValue=(v:unknown):unknown=>{if(v&&typeof v==='object'&&'result' in v)return(v as {result:unknown}).result;if(v&&typeof v==='object'&&'richText' in v)return(v as {richText:{text:string}[]}).richText.map(x=>x.text).join('');return v;};
const isoDate=(raw:unknown):string=>{ const v=cellValue(raw);if(v instanceof Date)return v.toISOString().slice(0,10); if(typeof v==='number'){const d=new Date(Date.UTC(1899,11,30)+v*86400000);return Number.isNaN(d.valueOf())?'':d.toISOString().slice(0,10);} const s=String(v||'').trim(); return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:''; };
const decimal=(v:unknown):string=>{if(typeof v==='number'&&Number.isFinite(v))return Math.abs(v).toFixed(4).replace(/\.?0+$/,'');let s=String(v||'').trim().replace(/\s/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.').replace(/[^0-9.()\-]/g,'');if(/^\(.*\)$/.test(s))s=s.slice(1,-1);s=s.replace(/^-/, '');return /^(0|[1-9]\d*)(\.\d{1,4})?$/.test(s)?s:'';};
const currencyFrom=(values:unknown[])=>{const text=values.map(v=>String(v||'')).join(' ').toUpperCase();const code=text.match(/(?:^|[^A-Z])(EUR|USD|GBP|CHF|PLN|UAH)(?:[^A-Z]|$)/)?.[1];return code||(text.includes('$')?'USD':text.includes('£')?'GBP':'EUR');};
export async function parseWorkbook(file: string): Promise<{ rows: ImportRow[]; rejected: Rejection[]; warnings: Rejection[]; counts: Record<string,{accepted:number;rejected:number}> }> {
  const workbook=new ExcelJS.Workbook();await workbook.xlsx.readFile(file); const rows:ImportRow[]=[];const rejected:Rejection[]=[];const warnings:Rejection[]=[];const counts:Record<string,{accepted:number;rejected:number}>={};
  for(const worksheet of workbook.worksheets){const sheet=worksheet.name;counts[sheet]={accepted:0,rejected:0};const matrix:unknown[][]=[];worksheet.eachRow({includeEmpty:true},row=>matrix.push(Array.from({length:Math.max(row.cellCount,worksheet.columnCount)},(_,i)=>cellValue(row.getCell(i+1).value))));if(!matrix.length)continue;
    let headerIndex=matrix.findIndex(r=>Array.isArray(r)&&r.some(v=>headers[String(v||'').trim().toLowerCase()]));if(headerIndex<0&&!/tax/i.test(sheet)){rejected.push({sheet,row:1,reason:'HEADER_UNMAPPED'});counts[sheet].rejected++;continue;}
    const headerlessTaxes=headerIndex<0;const width=headerlessTaxes?Math.max(...matrix.map(r=>r.length)):(matrix[headerIndex] as unknown[]).length;const map=headerlessTaxes?[]:(matrix[headerIndex] as unknown[]).map(v=>headers[String(v||'').trim().toLowerCase()]);
    // Historical sheets have stable positional layouts but drifting labels.
    const fallback=headerlessTaxes?['transactionDate','description','counterparty','amount','amountEur']:width>=10?['transactionDate','paidDate','counterparty','description','amountEur','amount','statementRef','quantity','comment','subtype','entryType','period','category']:['transactionDate','paidDate','counterparty','description','amountEur','amount','statementRef'];
    fallback.forEach((field,index)=>{if(!map[index]&&index<width)map[index]=field});
    for(let i=headerIndex+1;i<matrix.length;i++){const raw=matrix[i] as unknown[];if(!raw||!raw.slice(0,width).some(v=>v!==undefined&&v!==null&&String(v).trim()))continue;const value:Record<string,unknown>={};map.forEach((k,j)=>{if(k)value[k]=raw[j]});
      if(!isoDate(value.transactionDate||value.paidDate)&&!decimal(value.amount||value.amountEur)&&!String(value.counterparty||value.description||'').trim())continue;
      const transactionDate=isoDate(value.transactionDate||value.paidDate);const amount=decimal(value.amount||value.amountEur);const counterparty=String(value.counterparty||'').trim();const description=String(value.description||counterparty).trim();const currency=String(value.currency||currencyFrom([value.amount,value.amountEur])).trim().toUpperCase();
      const reason=!transactionDate?'INVALID_DATE':!amount?'INVALID_AMOUNT':!counterparty&&!/tax/i.test(sheet)?'MISSING_COUNTERPARTY':!description?'MISSING_DESCRIPTION':!/^[A-Z]{3}$/.test(currency)?'INVALID_CURRENCY':'';
      if(reason){rejected.push({sheet,row:i+1,reason});counts[sheet].rejected++;continue;}
      const sourceKey=createHash('sha256').update(`${sheet}\0${i+1}\0${transactionDate}\0${amount}\0${currency}`).digest('hex');
      const record:any={transactionDate,counterparty:counterparty||'Tax authority',description,amount,currency,sourceType:'xlsx-import',sourceKey};
      for(const k of ['paidDate','amountEur','statementRef','comment','entryType','subtype','period','category'])if(value[k]!=null&&String(value[k]).trim()){if(k==='paidDate'||k==='amountEur'){const normalized=k==='paidDate'?isoDate(value[k]):decimal(value[k]);if(normalized)record[k]=normalized;else warnings.push({sheet,row:i+1,reason:k==='paidDate'?'OPTIONAL_PAID_DATE_UNMAPPED':'OPTIONAL_AMOUNT_EUR_UNMAPPED'});}else record[k]=String(value[k]).trim();}
      Object.defineProperty(record,'sourceCoordinate',{value:`${sheet}:${i+1}`,enumerable:false});
      if(value.quantity!=null&&Number.isSafeInteger(Number(value.quantity)))record.quantity=Number(value.quantity);rows.push(record);counts[sheet].accepted++;
    }
  } return {rows,rejected,warnings,counts};
}
export async function writeRows(rows: ImportRow[], options:{api:string;secret:string;portalUsername?:string;portalPassword?:string;concurrency?:number;ratePerMinute?:number;fetcher?:typeof fetch;sleep?:(ms:number)=>Promise<void>;now?:()=>number}) {
  const fetcher=options.fetcher||fetch, sleep=options.sleep||(ms=>new Promise(r=>setTimeout(r,ms))), now=options.now||Date.now, queue=[...rows];let created=0,duplicates=0;
  const rate=Math.max(1,Math.min(options.ratePerMinute||50,60)), interval=60000/rate;let nextAt=now();
  const portalAuthorization=options.portalUsername&&options.portalPassword?`Basic ${Buffer.from(`${options.portalUsername}:${options.portalPassword}`).toString('base64')}`:undefined;
  async function pace(){const scheduled=Math.max(nextAt,now());nextAt=scheduled+interval;const delay=scheduled-now();if(delay>0)await sleep(delay);}
  async function worker(){for(;;){const row=queue.shift();if(!row)return;let response:Response|undefined;for(let attempt=0;attempt<6;attempt++){await pace();response=await fetcher(`${options.api.replace(/\/$/,'')}/api/bookkeeping/ingest`,{method:'POST',headers:{'content-type':'application/json','x-bookkeeping-ingestion-key':options.secret,'idempotency-key':row.sourceKey,...(portalAuthorization?{authorization:portalAuthorization}:{})},body:JSON.stringify(row)});if(![429,500,502,503,504].includes(response.status))break;const retryAfter=Number(response.headers.get('retry-after'));const backoff=Number.isFinite(retryAfter)&&retryAfter>0?retryAfter*1000:Math.min(1000*2**attempt,30000);await sleep(backoff);}if(!response?.ok){let reason=`HTTP_${response?.status||0}`;try{const failure=await response.json() as {fields?:unknown};const allowed=new Set(['transactionDate','paidDate','counterparty','description','amount','currency','amountEur','quantity','statementRef','comment','entryType','subtype','period','category','sourceType','sourceKey']);if(Array.isArray(failure.fields)){const fields=failure.fields.filter((v):v is string=>typeof v==='string'&&allowed.has(v));if(fields.length)reason=`VALIDATION_${fields.join('_').toUpperCase()}`;}}catch{}throw new Error(`Import stopped: ${row.sourceCoordinate||'unknown-row'} ${reason} HTTP ${response?.status||0}`);}const result=await response.json() as {duplicate:boolean};result.duplicate?duplicates++:created++;}}
  await Promise.all(Array.from({length:Math.max(1,Math.min(options.concurrency||4,8))},worker));return {accepted:rows.length,created,duplicates};
}
async function main(){const args=process.argv.slice(2);const file=args.find(a=>!a.startsWith('--'))||'.tmp/bookkeeping.xlsx';const parsed=await parseWorkbook(file);console.log(JSON.stringify({mode:args.includes('--write')?'write':'dry-run',counts:parsed.counts,rejected:parsed.rejected,warnings:parsed.warnings}));if(!args.includes('--write'))return;
  const api=process.env.BOOKKEEPING_API_URL, secret=process.env.BOOKKEEPING_INGESTION_KEY, env=process.env.BOOKKEEPING_TARGET_ENV, confirm=args.find(a=>a.startsWith('--confirm='))?.slice(10);if(!api||!secret||!env||confirm!==env)throw new Error('Write requires API URL, ingestion key, target environment, and matching --confirm');
  const portalUsername=process.env.BOOKKEEPING_PORTAL_USERNAME,portalPassword=process.env.BOOKKEEPING_PORTAL_PASSWORD;if(Boolean(portalUsername)!==Boolean(portalPassword))throw new Error('Portal username and password must be provided together');
  const verified=await writeRows(parsed.rows,{api,secret,portalUsername,portalPassword,concurrency:Number(process.env.BOOKKEEPING_IMPORT_CONCURRENCY||4),ratePerMinute:Number(process.env.BOOKKEEPING_IMPORT_RATE_PER_MINUTE||50)});
  const session=process.env.BOOKKEEPING_SESSION_TOKEN;if(!session&&!portalUsername)throw new Error('Write verification requires BOOKKEEPING_SESSION_TOKEN or portal credentials');const verificationAuthorization=portalUsername&&portalPassword?`Basic ${Buffer.from(`${portalUsername}:${portalPassword}`).toString('base64')}`:`Bearer ${session}`;const response=await fetch(`${api.replace(/\/$/,'')}/api/bookkeeping/transactions`,{headers:{authorization:verificationAuthorization}});if(!response.ok)throw new Error(`Verification stopped: HTTP ${response.status}`);const listed=await response.json() as {items:ImportRow[]};const imported=new Set(listed.items.filter(i=>i.sourceType==='xlsx-import').map(i=>i.sourceKey));if(parsed.rows.some(r=>!imported.has(r.sourceKey)))throw new Error('Verification failed: imported source keys missing');console.log(JSON.stringify({verified}));}
if(import.meta.url===`file://${process.argv[1]}`)main().catch(e=>{console.error((e as Error).message);process.exitCode=1});
