import { afterEach, test } from 'node:test';
import assert from 'node:assert/strict';
import { officialProviders, publicationConfig, setInvoiceProviderClientsForTests, sheetValues, type PublicationConfig } from '../src/invoices/providers';
import type { Invoice } from '../src/invoices/model';
const config:PublicationConfig={brokerUrl:'https://broker.example.invalid',brokerCredential:'synthetic-secret',agent:'invoice-test',googleConnection:'google-sheets',googleAccountId:'google-test-account',dropboxConnection:'dropbox',dropboxAccountId:'dropbox-test-account',spreadsheetId:'synthetic-workbook',sheetTab:'2026',dropboxRoot:'/synthetic-expenses',monthFolderPrefix:'workspace-'};
const headers=['Date sent','Date paid','Provider','What','Price, $','Price, EUR','Statement','Count','Comment','Entry Type','Type','Period','Category'];
afterEach(()=>{delete process.env.INVOICE_PUBLICATION_CONFIG;setInvoiceProviderClientsForTests({});});
function response(body:unknown,status=200,headers:Record<string,string>={}) {return new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json',...headers}});}
function fakeFetch(overrides:{account?:boolean;scope?:boolean;brokerStatus?:number;wrongHeader?:boolean}={},inspect?:(url:string,init:RequestInit)=>void):typeof fetch {
  return (async(url:unknown,init:RequestInit)=>{
    const path=String(url);inspect?.(path,init);
    if(path.endsWith('/api/agent/token')) {const body=JSON.parse(String(init.body));assert.equal(body.agent,config.agent);assert.equal((init.headers as Record<string,string>).Authorization,`Bearer ${config.brokerCredential}`);const google=body.connection_id==='google-sheets';return response({access_token:'synthetic-access',provider_account_id:overrides.account?'wrong-account':google?config.googleAccountId:config.dropboxAccountId,scope:overrides.scope?'read-only':google?'https://www.googleapis.com/auth/spreadsheets':'files.content.write files.content.read files.metadata.read'},overrides.brokerStatus || 200);}
    if(path.includes('sheets.googleapis.com')) return response(init.method==='PUT'?{}:{values:[overrides.wrongHeader?['wrong header']:headers]});
    if(path.includes('/get_metadata')) return response({'.tag':'folder'});
    throw new Error('unexpected-test-request');
  }) as typeof fetch;
}
test('managed base64 configuration decodes without echoing credentials',async()=>{process.env.INVOICE_PUBLICATION_CONFIG=Buffer.from(JSON.stringify(config)).toString('base64');assert.deepEqual(await publicationConfig(),config);});
test('official broker response validates account and required scopes before destination calls',async()=>{for(const options of [{account:true},{scope:true},{brokerStatus:403}]){let destinationCalls=0;setInvoiceProviderClientsForTests({fetch:fakeFetch(options,url=>{if(!url.startsWith(config.brokerUrl))destinationCalls++;})});const checks=await (await officialProviders(config)).readiness();assert.ok(checks.filter(c=>c.name.includes('broker')).every(c=>!c.ready));assert.equal(destinationCalls,0);assert.ok(checks.every(c=>!c.message.includes(config.brokerCredential)));}});
test('wrong headers block configuration readiness',async()=>{setInvoiceProviderClientsForTests({fetch:fakeFetch({wrongHeader:true})});assert.ok((await(await officialProviders(config)).readiness()).some(c=>c.name==='sheet-headers'&&!c.ready));});
test('official sheet requests numeric RAW cells and unformatted readback, dynamic optional comment',async()=>{const calls:Array<{url:string;init:RequestInit}>=[];setInvoiceProviderClientsForTests({fetch:fakeFetch({},(url,init)=>calls.push({url,init}))});const adapter=await officialProviders(config);const layout=await adapter.sheetLayout();const invoice={id:'b'.repeat(64),fields:{transactionDate:'2026-10-01',paidDate:'2026-10-02',counterparty:'Example',description:'Subscription',currency:'USD',amount:'25.50',amountEur:'23.05',quantity:1,paymentEvidence:'Operator confirmed actual bank value'},source:{artifactId:'synthetic-doc'}} as Invoice;await adapter.writeRow(2,sheetValues(invoice,layout.headers));await adapter.readRow(2);const write=calls.find(c=>c.init.method==='PUT')!;const cells=JSON.parse(String(write.init.body)).values[0];assert.equal(cells[4],-25.5);assert.equal(cells[5],-23.05);assert.equal(cells[7],1);assert.equal(cells[9],'expense');assert.ok(cells[6].includes(invoice.id));assert.match(write.url,/valueInputOption=RAW/);assert.ok(calls.filter(c=>c.url.includes('sheets.googleapis.com')&&c.init.method==='GET').every(c=>c.url.includes('valueRenderOption=UNFORMATTED_VALUE')));});
