const { test, expect } = require('@playwright/test');
const { spawn } = require('child_process');
const http = require('http');
const path = require('path');
const PORT = 3016, BASE_URL = `http://127.0.0.1:${PORT}`;
let child;
const wait = () => new Promise((resolve, reject) => { const end=Date.now()+30000;(function poll(){const req=http.get(`${BASE_URL}/api/health`,res=>{res.resume();resolve();});req.on('error',()=>Date.now()>end?reject(new Error('portal timeout')):setTimeout(poll,200));})(); });
test.describe('production sponsor CRM portal', () => {
  test.beforeAll(async () => { child=spawn('npx',['tsx','scripts/test-server.ts'],{cwd:path.resolve(__dirname,'..'),env:{...process.env,NODE_ENV:'test',IS_LOCAL:'true',SKIP_AUTH:'true',DATAOPS_DOCS_DOMAIN:'1',DTC_OFFLINE:'1',FRONTEND_ROOT:path.resolve(__dirname,'..','..','frontend'),PORT:String(PORT)},stdio:['ignore','pipe','pipe'],detached:true});await wait(); });
  test.afterAll(() => { try { process.kill(-child.pid,'SIGTERM'); } catch {} });
  test('renders clean loading, populated, history, alerts, error and mobile states', async ({ browser }) => {
    const context=await browser.newContext({baseURL:BASE_URL}),page=await context.newPage();let release;const gate=new Promise(resolve=>release=resolve);
    const organization={id:'org-1',displayName:'Synthetic Sponsor',version:1},contact={id:'contact-1',organizationId:'org-1',name:'Synthetic Contact',primary:true,version:1},booking={id:'booking-1',organizationId:'org-1',primaryContactId:'contact-1',slotType:'main',status:'confirmed',plannedPublicationDate:'2026-08-20',materialDeadline:'2026-08-10',nextActionDate:'2026-08-01',bundleId:'newsletter-bundle-1',version:2};
    await page.route('**/work/api/sponsor-crm/**',async route=>{const pathname=new URL(route.request().url()).pathname;if(pathname.endsWith('/organizations'))return route.fulfill({json:{items:[organization]}});if(pathname.endsWith('/contacts'))return route.fulfill({json:{items:[contact]}});if(pathname.endsWith('/bookings'))return route.fulfill({json:{items:[booking]}});if(pathname.endsWith('/history'))return route.fulfill({json:{items:[{id:'h1',oldStatus:null,newStatus:'inquiry',actorId:'synthetic-operator',createdAt:'2026-07-01T00:00:00Z'},{id:'h2',oldStatus:'inquiry',newStatus:'confirmed',actorId:'synthetic-operator',note:'Synthetic confirmation',createdAt:'2026-07-02T00:00:00Z'}]}});return route.fulfill({status:404,json:{error:'Synthetic route missing'}});});
    await page.route('**/work/api/notifications',async route=>{await gate;return route.fulfill({json:{notifications:[{id:'alert-1',message:'Sponsor booking materials are missing 10 days before publication',dueAt:'2026-08-20',dismissed:false,metadata:{sponsorBookingId:'booking-1'}}]}});});
    await page.goto('/');await page.getByRole('button',{name:'Sponsors'}).click();await expect(page.getByText('Loading sponsor CRM…')).toBeVisible();await page.locator('.sponsor-crm-surface').screenshot({path:'.tmp/sponsor-crm-production-loading.png'});release();await expect(page.locator('[data-crm-orgs]')).toContainText('Synthetic Sponsor');await expect(page.getByText(/materials are missing/)).toBeVisible();await page.locator('.crm-layout').screenshot({path:'.tmp/sponsor-crm-production-populated.png'});await page.getByRole('button',{name:'Open booking'}).first().click();await expect(page.getByText('inquiry → confirmed')).toBeVisible();await page.waitForTimeout(250);await page.locator('[data-crm-detail] .crm-card').screenshot({path:'.tmp/sponsor-crm-production-history.png'});await page.locator('[data-crm-alerts] .crm-card').screenshot({path:'.tmp/sponsor-crm-production-alert.png'});
    await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.body.classList.remove('sidebar-open'));await expect.poll(async()=>{const box=await page.locator('#sidebar').boundingBox();return box?box.x+box.width:0;}).toBeLessThanOrEqual(0);expect((await page.evaluate(()=>document.documentElement.scrollWidth))).toBeLessThanOrEqual(390);await page.screenshot({path:'.tmp/sponsor-crm-production-mobile.png',fullPage:true});await context.close();
    const errorContext=await browser.newContext({baseURL:BASE_URL}),errorPage=await errorContext.newPage();await errorPage.route('**/work/api/sponsor-crm/**',route=>route.fulfill({status:403,json:{error:'Synthetic permission denied'}}));await errorPage.route('**/work/api/notifications',route=>route.fulfill({json:{notifications:[]}}));await errorPage.goto('/');await errorPage.getByRole('button',{name:'Sponsors'}).click();await expect(errorPage.getByRole('status')).toContainText('Permission or API error');await errorPage.waitForTimeout(250);await errorPage.locator('.sponsor-crm-surface').screenshot({path:'.tmp/sponsor-crm-production-error.png'});await errorContext.close();
  });
});
