import type { DynamoDBDocumentClient } from '@aws-sdk/lib-dynamodb';
import type { LambdaEvent,LambdaResponse } from '../types';
import { createCalendarItem,deleteCalendarItem,dismissCalendarAlert,getCalendarItem,isCalendarAlertDismissed,listCalendarItems,updateCalendarItem } from '../db/calendar';
import { calendarAlerts } from '../calendar/alerts';
import { builtInHolidayGeneration,holidayMetadata,holidaySnapshot } from '../calendar/holidays';
import { persistHolidayGeneration,readHolidayGeneration } from '../db/calendarHolidays';
import { projectCalendarOverlays,registerCalendarOverlayProvider } from '../calendar/overlays';
import { newsletterCalendarOverlay } from '../calendar/newsletterOverlay';
const json=(statusCode:number,body:unknown):LambdaResponse=>({statusCode,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
const DATE=/^\d{4}-\d{2}-\d{2}$/, TYPES=new Set(['podcast-live','podcast-release','webinar','workshop','book-of-the-week','course','cohort','other']), STATUSES=new Set(['tentative','confirmed','announced','published','cancelled']), ID=/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/;
const realDate=(v:any)=>typeof v==='string'&&DATE.test(v)&&new Date(`${v}T00:00:00Z`).toISOString().slice(0,10)===v;
const days=(a:string,b:string)=>(Date.parse(`${b}T00:00:00Z`)-Date.parse(`${a}T00:00:00Z`))/86400000;
const parse=(event:LambdaEvent)=>{try{return event.body?JSON.parse(String(event.body)):null}catch{return null}};
const actor=(event:LambdaEvent)=>Object.entries(event.headers||{}).find(([k])=>k.toLowerCase()==='x-user-id')?.[1]||'authenticated-operator';
const writable=new Set(['activityType','title','status','allDay','startDate','endDate','startsAt','endsAt','timeZone','bundleId','templateId','url','notes','sourceType','sourceKey','version']);
function validate(body:any,partial=false){
 if(!body||typeof body!=='object'||Array.isArray(body))return 'Request body is required'; const unknown=Object.keys(body).find(k=>!writable.has(k)); if(unknown)return `Unknown field: ${unknown}`;
 if((!partial||body.activityType!==undefined)&&!TYPES.has(body.activityType))return 'Invalid activityType'; if((!partial||body.status!==undefined)&&!STATUSES.has(body.status))return 'Invalid status';
 if((!partial||body.title!==undefined)&&(typeof body.title!=='string'||!body.title.trim()||body.title.length>200))return 'Invalid title'; if((!partial||body.allDay!==undefined)&&typeof body.allDay!=='boolean')return 'Invalid allDay';
 if(body.allDay===true||(!partial&&body.allDay)){ if(!realDate(body.startDate)||!realDate(body.endDate)||body.startDate>body.endDate||days(body.startDate,body.endDate)>366)return 'Invalid all-day range'; if(body.startsAt!=null||body.endsAt!=null)return 'All-day items cannot contain timestamps'; }
 if(body.allDay===false||(!partial&&!body.allDay)){ if(typeof body.startsAt!=='string'||typeof body.endsAt!=='string'||!/(Z|[+-]\d\d:\d\d)$/.test(body.startsAt)||!/(Z|[+-]\d\d:\d\d)$/.test(body.endsAt)||isNaN(Date.parse(body.startsAt))||isNaN(Date.parse(body.endsAt))||Date.parse(body.startsAt)>=Date.parse(body.endsAt)||Date.parse(body.endsAt)-Date.parse(body.startsAt)>366*86400000)return 'Invalid timed range; explicit UTC offset is required'; if(body.timeZone!=='Europe/Berlin')return 'timeZone must be Europe/Berlin';for(const name of ['startsAt','endsAt'])if(!body[name].endsWith('Z')){const p=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date(body[name])).replace(' ','T');if(p!==body[name].slice(0,16))return `Invalid ${name}: local time is outside the Europe/Berlin offset`;} if(body.startDate!=null||body.endDate!=null)return 'Timed items cannot contain date-only fields'; }
 for(const k of ['bundleId','templateId'])if(body[k]!=null&&!ID.test(body[k]))return `Invalid ${k}`; for(const [k,n] of [['notes',2000],['sourceType',100],['sourceKey',300]] as [string,number][])if(body[k]!=null&&(typeof body[k]!=='string'||body[k].length>n))return `Invalid ${k}`;
 if(body.url!=null){try{if(new URL(body.url).protocol!=='https:')return 'Invalid url'}catch{return 'Invalid url'}} return '';
}
function berlinDate(instant:string){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date(instant)),get=(type:string)=>parts.find(p=>p.type===type)!.value;return `${get('year')}-${get('month')}-${get('day')}`;}
function normalize(body:any,existing?:any){const merged={...existing,...body}; if(merged.allDay){merged.startKey=merged.startDate;merged.endKey=merged.endDate;merged.timeZone='Europe/Berlin';delete merged.startsAt;delete merged.endsAt;}else{merged.startsAt=new Date(merged.startsAt).toISOString();merged.endsAt=new Date(merged.endsAt).toISOString();merged.startKey=berlinDate(merged.startsAt);merged.endKey=berlinDate(merged.endsAt);delete merged.startDate;delete merged.endDate;} return merged;}
function domain(value:any){return Object.fromEntries(Object.entries(value).filter(([key])=>writable.has(key)));}
function range(event:LambdaEvent){const q=event.queryStringParameters||{},from=q.from,to=q.to;if(!realDate(from)||!realDate(to)||from!>to||days(from!,to!)>366)return null;return {from:from!,to:to!};}
export async function handleCalendarRoutes(path:string,method:string,event:LambdaEvent,client:DynamoDBDocumentClient){
 if(path==='/api/calendar-items/holidays/sync'){if(method!=='POST')return json(405,{error:'Method not allowed'});try{const generation=await persistHolidayGeneration(client,builtInHolidayGeneration());return json(200,{generationId:generation.generationId,revision:generation.revision,freshAsOf:generation.freshAsOf,count:generation.occurrences.length})}catch{return json(503,{error:'Holiday refresh failed; last-known-good retained'})}}
 const dismissal=path.match(/^\/api\/calendar-items\/alerts\/([^/]+)\/dismiss$/);if(dismissal){if(method!=='POST')return json(405,{error:'Method not allowed'});const fingerprint=decodeURIComponent(dismissal[1]);if(!fingerprint||fingerprint.length>1000)return json(400,{error:'Invalid alert fingerprint'});await dismissCalendarAlert(client,fingerprint,actor(event));return json(200,{dismissed:true});}
 const r=range(event), overlay=path==='/api/calendar-items/overlays', match=path.match(/^\/api\/calendar-items(?:\/([^/]+))?$/);
 if(overlay){if(method!=='GET')return json(405,{error:'Method not allowed'});if(!r)return json(400,{error:'Invalid or unbounded range'});registerCalendarOverlayProvider(newsletterCalendarOverlay(client));return json(200,{items:await projectCalendarOverlays(r.from,r.to)});}
 if(!match)return json(404,{error:'Not found'}); const id=match[1]&&decodeURIComponent(match[1]);
 if(method==='GET'&&!id){if(!r)return json(400,{error:'Invalid or unbounded range'});let items=await listCalendarItems(client,r.from,r.to);const q=event.queryStringParameters||{};if(q.activityType){if(!TYPES.has(q.activityType))return json(400,{error:'Invalid activityType'});items=items.filter(i=>i.activityType===q.activityType)}if(q.status){if(!STATUSES.has(q.status))return json(400,{error:'Invalid status'});items=items.filter(i=>i.status===q.status)}const generation=await readHolidayGeneration(client),holidays=(generation?.occurrences||holidaySnapshot(r.from,r.to)).filter(h=>h.startDate<=r.to&&h.endDate>=r.from),base=generation?{region:'DE-BE',freshAsOf:generation.freshAsOf,horizon:generation.horizon,stale:(Date.now()-Date.parse(`${generation.freshAsOf}T00:00:00Z`))>180*86400000,outOfHorizon:r.from<generation.horizon.from||r.to>generation.horizon.to,sources:generation.sourceUrls,lastKnownGood:true,generationId:generation.generationId,persistent:true}:holidayMetadata(r.from,r.to),computed=calendarAlerts(items,holidays),dismissed=await Promise.all(computed.map(a=>isCalendarAlertDismissed(client,a.fingerprint)));return json(200,{items,holidays,holidayMetadata:base,alerts:computed.filter((_,i)=>!dismissed[i]),timeZone:'Europe/Berlin'});}
 if(method==='GET'&&id){const item=await getCalendarItem(client,id);return item?json(200,item):json(404,{error:'Not found'});}
 if(method==='POST'&&!id){const body=parse(event),error=validate(body);if(error)return json(400,{error});try{const result=await createCalendarItem(client,normalize(body),actor(event));return json(result.duplicate?200:201,result)}catch(e){return json((e as any).statusCode||500,{error:(e as Error).message})}}
 if(!id)return json(405,{error:'Method not allowed'});const existing=await getCalendarItem(client,id);if(!existing)return json(404,{error:'Not found'});
 const body=parse(event);if(method==='PUT'){const error=validate(body,true);if(error)return json(400,{error});if(body.version!==existing.version)return json(409,{error:'Version conflict',currentVersion:existing.version});const merged=normalize(domain({...existing,...body})),fullError=validate(domain(merged));if(fullError)return json(400,{error:fullError});try{return json(200,await updateCalendarItem(client,existing,merged,actor(event)))}catch{return json(409,{error:'Version conflict'})}}
 if(method==='DELETE'){if(!body||body.version!==existing.version)return json(409,{error:'Version conflict',currentVersion:existing.version});try{await deleteCalendarItem(client,existing);return {statusCode:204,headers:{},body:''}}catch{return json(409,{error:'Version conflict'})}}
 return json(405,{error:'Method not allowed'});
}
