import {
  addDaysIso, canonicalWorkspaceUrl,
  cardAnchorTone, cardsHeaderViewModel, compareIsoDate, dedupeWorkTasks,
  describeRecurringRun, formatCardAnchorLabel,
  formatShortDate,
  formatTaskDateMeta, groupCardItemsByMonth, groupCardItemsByStage,
  hasApprovedArtifactEvidence, hasTaskFileEvidence, isActiveWorkCard,
  isArchivedWorkCard, isFollowUpDueTask, isOpenWorkTask,
  isTaskDueToday, isTaskOverdue, isWaitingOrFollowUpTask, isoDayDistance,
  parseWorkspaceHash, summarizeCardProgress, taskDate, taskProofState,
  taskRequiresApprovedArtifact, tasksFromWorkPayload, tasksSectionTitle,
  todayIsoDate, workCardTitle, workTaskTitle, workflowTaskGroups,
  workspaceHashPath, workspaceRouteFor,
} from "../core/workspace.js";
import {
  assistantJobsFromPayload, cardsFromWorkPayload,
  compareQualityFindings, currentOperatorIdFromPayload,
  dedupeQualityFindings,
  emptyOperationsAssistantSnapshot, emptyOperationsDocsSnapshot,
  emptyOperationsQualitySnapshot, emptyOperationsRecurringSnapshot,
  emptyOperationsReviewSnapshot,
  emptyOperationsWorkSnapshot,
  findingMatchesCard,
  labelizeWorkValue, normalizeOperationsQualitySnapshot,
  normalizeQualityFinding, normalizeTemplateMatchValue,
  recurringConfigsFromPayload, settledPayload, taskHasClearProofInstruction,
  taskNeedsProofInstruction, usersFromWorkPayload,
} from "../core/operations-model.js";
import { createWorkModel } from "../core/work-model.js";
import { createFinanceSurface } from "../surfaces/finance/index.js";
import { createAdminSurface, createOperationsSurface } from "../surfaces/operations/index.js";
import { createPlanningSurface } from "../surfaces/planning.js";
import { createTasksSurface } from "../surfaces/tasks/index.js";
import { createWorkDetailSurface } from "../surfaces/work-detail/index.js";
import { createKnowledgeSurface } from "../surfaces/knowledge/index.js";
import { createDocumentEditor } from "../surfaces/document-editor/index.js";
import { createReviewSurface } from "../surfaces/review/index.js";
import { createOperatingModelSurface } from "../surfaces/operating-model.js";
import { createApiClient, resolveApiBase } from "../shell/api.js";
import { createFeedbackShell } from "../shell/feedback.js";
import { createNavigationShell } from "../shell/navigation.js";
import { initializeAppShell } from "../shell/bootstrap.js";
import { queryAppDom } from "../shell/dom-bindings.js";
import { bindApplicationEvents } from "./application-events.js";
import { createOperationKernel } from "./operation-kernel.js";
import { createApplicationShells } from "./shell-composition.js";
import { createWorkspaceState } from "../runtime/workspace-state.js";
import { createSurfaceBridge, createSurfaceComposition } from "./surface-composition.js";
let knowledgeSurface;
let documentEditorSurface;
let reviewSurface;
let operatingModelSurface;
let navigationShell;

const surfaceBridge = createSurfaceBridge();
const {
  applyWorkspaceRoute, beginDocumentNavigation, canLeaveDocumentEditor, closeCustomSelects, clearDocumentFilters,
  closeDiff, closeLightbox, closeQuickNav, createDocument, deleteCurrentDoc, discardAllDrafts, discardDraft, docPathFromLocation,
  emptyNote, enhanceSelect, enterRenderedMode, escapeRegex, folderExists, folderPathFromLocation, getActiveWorkspaceRoute,
  getActiveWorkspaceRouteToken, getPendingLegacyRoute, getWorkspaceEntityState, handleClipboardPaste, humanizeOptionLabel,
  isWorkspaceRouteFresh, labelForPath, listDraftPaths, loadDocuments, localDocPathFromHref, navigateCanonicalWorkspace,
  onFilterChange, openHistory, openDocMenu, openDocument, openLintReport, openQuickNav, populateFilterOptions,
  refreshChangesPanel, refreshDocuments, refreshKnowledgeStatus, renameCurrentDoc, renderDocsSurface, renderProcessesSurface,
  renderUnifiedSearchSurface, resolveDocReference, resolveMarkdownDocLink, restoreDocumentFilters, saveAllDrafts,
  saveCurrentDocument, setFolderUrl, setSaveState, setWorkspaceEntityState, showCreate, showLibrary,
  storeDraft, syncLibraryRouteTitle, syncTitleToMarkdown, updateQuickNavMatches, updateSaveState,
  titleFromMarkdown, toggleViewMode, updateCustomSelect, updateFilterSummary,
  updateViewToggleAvailability, visibleDocUrl, closeHistory, resizeDocumentTitle,
} = surfaceBridge;
const API_BASE = resolveApiBase({ documentRef: document, windowRef: window });
const { apiUrl, request } = createApiClient({
  apiBase: API_BASE,
  fetchImpl: (...args) => fetch(...args),
  storage: localStorage,
});
const workspaceState = createWorkspaceState({
  emptyOperationsAssistantSnapshot,
  emptyOperationsDocsSnapshot,
  emptyOperationsQualitySnapshot,
  emptyOperationsRecurringSnapshot,
  emptyOperationsReviewSnapshot,
  emptyOperationsWorkSnapshot,
  getAccountIdentityState: () => getAccountIdentityState(),
  getWorkspaceEntityState,
  setWorkspaceEntityState,
});
const {
  documentState,
  knowledgeState,
  operationsSurfaceState,
  qualityFiltersState,
  reviewSurfaceState,
  tasksSurfaceState,
  workDetailState,
  workModelState,
} = workspaceState;

const dom = queryAppDom(document);
const {
  body, sidebar, sidebarScrim, mobileMenuButton,
  sidebarCloseButton, sidebarCollapseButton, themeToggleButton,
  sidebarExpandButton, changesSection, changesCount, changesStatus,
  changesList, changesSaveAll, changesDiscardAll, lintOpenButton,
  lintSummary, lintModal, lintBackdrop, lintModalBody, lintModalClose,
  knowledgeSection, knowledgeStatusText, historyButton, knowledgeStatusButton, historyModal, historyClose,
  historyPath, historySearchForm, historyStatus, historyVersions, historyComparison,
  searchForm, searchInput,
  domainFilter, typeFilter, systemFilter, tagFilter,
  filtersSection, filterCount, helpModal, helpClose,
  documentList, pageShell, documentRowTemplate,
  mobileTitle,
  editorInlineStatus, editorSaveState, editorDiscardButton,
  editorSaveButton, documentTitle, documentPath,
  editor, editorView, renderedView, viewToggleButton, docMenuButton,
  newDocForm, newDocPath,
  newDocTitle, newDocType, newDocSummary, workspaceNavButtons,
  tasksNavSectionButtons, docContextReturn,
  docState,
  taskPanel, taskPanelTitle, taskPanelBody, taskPanelClose, taskModalBackdrop,
  cardPanel, cardPanelTitle, cardPanelBody, cardPanelClose,
  cardModalBackdrop, diffModal, diffTitle, diffBody, diffClose, lightbox,
  lightboxImg, lightboxCaption, quickNav, quickNavInput, quickNavResults,
} = dom;
const {
  allWorkTasks,
  basename,
  canLeaveCurrentDocument,
  cleanPath,
  debounce,
  escapeHtml,
  isOperationsWorkspaceVisible,
  legacyViewToTasksSection,
  refreshOperationsRecurringSnapshot,
  renderOperationsWorkspace,
  setRouteTitle,
  setView,
  showWorkspaceSurface,
  syncWorkspaceNav,
  workApiUrl,
} = createSurfaceComposition({
  apiUrl,
  body,
  clearTimeoutImpl: clearTimeout,
  dedupeWorkTasks,
  emptyOperationsRecurringSnapshot,
  getCanLeaveDocumentEditor: () => canLeaveDocumentEditor,
  getCanLeaveFinanceSurface: () => canLeaveFinanceSurface,
  getKnowledgeSelectedFolder: () => knowledgeState.selectedFolder,
  getNormalizeOperationsRecurringSnapshot: () =>
    normalizeOperationsRecurringSnapshot,
  getRenderAdminSurfaceView: () => renderAdminSurfaceView,
  getRenderBookkeepingSurface: () => renderBookkeepingSurface,
  getRenderCalendarSurface: () => renderCalendarSurface,
  getRenderDocsSurface: () => renderDocsSurface,
  getRenderNewsletterSurface: () => renderNewsletterSurface,
  getRenderOperatingModel: () => operatingModelSurface?.renderOperatingModel || (() => undefined),
  getRenderReviewSurface: () =>
    reviewSurface?.renderReviewSurface || (() => undefined),
  getRenderSponsorCrmSurface: () => renderSponsorCrmSurface,
  getRenderTasksSurface: () => renderTasksSurface,
  getRenderDeviceSurfaceView: () => renderDeviceSurfaceView,
  getRenderUsersSurfaceView: () => renderUsersSurfaceView,
  getSearchValue: () => searchInput.value,
  isOpenWorkTask,
  mobileTitle,
  navigateCanonicalWorkspace,
  recurringConfigsFromPayload,
  refreshDocuments,
  request,
  searchInput,
  setTimeoutImpl: setTimeout,
  tasksFromWorkPayload,
  tasksNavSectionButtons,
  windowConsole: console,
  workspaceHashPath,
  workspaceNavButtons,
  workspaceState,
});
const {
  confirmDialog,
  renderEntityLoadState,
  renderEntityLoadingState,
  showUndoToast,
} = createFeedbackShell({
  clearTimeoutImpl: clearTimeout,
  documentRef: document,
  HTMLElementClass: HTMLElement,
  labelizeWorkValue,
  requestAnimationFrameImpl: requestAnimationFrame,
  setTimeoutImpl: setTimeout,
});
const {
  canLeaveFinanceSurface,
  renderBookkeepingSurface,
  renderSponsorCrmSurface,
} = createFinanceSurface({
  documentList,
  escapeHtml,
  formatTaskDateMeta,
  getPendingLegacyRoute,
  humanizeOptionLabel,
  isWorkspaceRouteFresh,
  navigateCanonicalWorkspace,
  request,
  renderEntityLoadState,
  setRouteTitle, todayIsoDate,
  workApiUrl,
});
const { renderCalendarSurface, renderNewsletterSurface } =
  createPlanningSurface({
    documentList,
    escapeHtml,
    request,
    setRouteTitle,
    todayIsoDate,
    workApiUrl,
  });
operatingModelSurface = createOperatingModelSurface({
  apiUrl,
  documentList,
  getActiveWorkspaceRoute,
  navigateCanonicalWorkspace,
  openDocument: (...args) => openDocument(...args),
  openHistory: (...args) => openHistory(...args),
  request,
  resolveDocReference: (...args) => resolveDocReference(...args),
  setRouteTitle,
});
const {
  account: {
    activeWorkOwner, activeWorkOwnerId, closeSettingsMenu,
    currentOperatorFromPayload, getAccountIdentityState,
    isSettingsMenuOpen, readLocalPreviewContext, refreshAccountIdentity,
  },
  notifications: notificationsShell,
  preferences: {
    closeSidebar, isMobileShell, openSidebar,
    restoreDarkMode, restoreSidebarCollapsed,
    setDarkMode, setSidebarCollapsed, syncSidebarShellState,
    syncThemeToggleLabel,
  },
} = createApplicationShells({
  canLeaveCurrentDocument,
  documentRef: document,
  dom,
  fetchImpl: (...args) => fetch(...args),
  formatShortDate,
  formatTaskDateMeta,
  HTMLElementClass: HTMLElement,
  isOperationsWorkspaceVisible,
  isWorkspaceRouteFresh,
  isoDayDistance,
  localStorageRef: localStorage,
  navigateCanonicalWorkspace,
  openTaskPanel: (...args) => openTaskPanel(...args),
  parseWorkspaceHash,
  requestAnimationFrameImpl: requestAnimationFrame,
  refreshDocuments,
  request,
  showWorkspaceSurface,
  todayIsoDate,
  windowRef: window,
  workApiUrl,
});
const {
  closeWorkBellPanel, openWorkBellPanel, refreshWorkBell,
} = notificationsShell;

const {
  buildOperationsFutureSections,
  buildOperationsReferenceLinks,
  currentOperatorIdForTodayScope,
  dedupeOperationItems,
  isAtRiskWorkflowSlug,
  isFollowUpDoc,
  isRecurringWorkflowSlug,
  isSyntheticCurrentOperatorId,
  isTaskAssignedTo,
  isWorkflowTemplateDoc,
  normalizeCardTaskMap,
  normalizeOperationsRecurringSnapshot,
  normalizeOperationsWorkSnapshot,
  operationItemFromCard,
  operationItemFromDoc,
  operationItemFromTask,
  operationItemFromTemplate,
  countLabel,
  openQualityFinding,
  operationsViewTitle,
  referenceCountLabel,
  renderDocsAvailabilityState,
  renderHonestState,
  renderOperationsLane,
  renderOperationsReference,
  renderOperationsRuntimeState,
  renderQualityFindingRow,
  renderSurfaceHeader,
  surfaceDescription,
  sortActiveWorkCards,
  sortWorkTasks,
  summarizeWorkflowTemplate,
  taskNextActionLabel,
  taskSortDate,
  taskSourceLabel,
  workflowPriority,
  workflowSlugFromDoc,
} = createOperationKernel({
  basename,
  cleanPath,
  documentRef: document,
  getRecurringConfigTitle: (...args) => recurringConfigTitle(...args),
  openCardPanel: (...args) => openCardPanel(...args),
  openDocument: (...args) => openDocument(...args),
  openHistory: (...args) => openHistory(...args),
  openTaskPanel: (...args) => openTaskPanel(...args),
  resolveAssigneeLabel: (...args) => resolveAssigneeLabel(...args),
  resolveDocReference: (...args) => resolveDocReference(...args),
  showWorkspaceSurface: (...args) => showWorkspaceSurface(...args),
  tasksSectionTitle,
  workspaceState,
});
const {
  buildOperationsWorkModel,
  buildProcessQualityModel,
  buildTaskProcessQualityFindings,
  refreshOperationsQualitySnapshot,
  refreshOperationsWorkSnapshot,
} = createWorkModel({
  activeWorkOwner,
  activeWorkOwnerId,
  allWorkTasks,
  apiUrl,
  buildOperationsFutureSections,
  buildOperationsReferenceLinks,
  compareQualityFindings,
  currentOperatorIdForTodayScope,
  currentOperatorIdFromPayload,
  dedupeQualityFindings,
  emptyOperationsQualitySnapshot,
  emptyOperationsWorkSnapshot,
  findingMatchesCard,
  isOperationsWorkspaceVisible,
  isWorkflowTemplateDoc,
  normalizeOperationsQualitySnapshot,
  normalizeOperationsRecurringSnapshot,
  normalizeOperationsWorkSnapshot,
  normalizeQualityFinding,
  normalizeTemplateMatchValue,
  operationItemFromCard,
  operationItemFromTask,
  operationItemFromTemplate,
  readLocalPreviewContext,
  refreshAccountIdentity,
  refreshDocuments,
  refreshWorkBell,
  request,
  resolveDocReference,
  settledPayload,
  state: workModelState,
  summarizeWorkflowTemplate,
  taskHasClearProofInstruction,
  taskNeedsProofInstruction,
  tasksFromWorkPayload,
  usersFromWorkPayload,
  workApiUrl,
  workflowPriority,
});
const {
  refreshUsersSurface,
  renderAdminSurface,
  renderAdminSurfaceView,
  renderUsersSurfaceView,
} = createAdminSurface({
  apiUrl,
  buildOperationsWorkModel,
  currentOperatorIdFromPayload,
  documentList,
  getActiveWorkspaceView: () => workspaceState.activeWorkspaceView,
  getActiveWorkspaceRouteToken,
  isWorkspaceRouteFresh,
  getOperationsQualitySnapshot: () => workspaceState.qualitySnapshot,
  getOperationsRecurringSnapshot: () => workspaceState.recurringSnapshot,
  getOperationsWorkSnapshot: () => workspaceState.workSnapshot,
  listDraftPaths,
  refreshDocuments,
  renderHonestState,
  renderSurfaceHeader,
  request,
  setRouteTitle,
  settledPayload,
  showWorkspaceSurface,
  surfaceDescription,
  usersFromWorkPayload,
  workApiUrl,
});
const {
  closeCardPanel,
  closeTaskPanel,
  dedupeArtifacts,
  defaultNextFollowUpDate,
  getTaskRouteContext,
  handleWorkspaceEntityModalKeydown,
  hydrateCardPanel,
  hydrateTaskPanel,
  openCardPanel,
  openTaskPanel,
  prepareCardPanel,
  prepareTaskPanel,
  renderArtifactList,
  resetCardPanel,
  resetTaskPanel,
  resolveAssigneeLabel,
  resolveCardLabel,
  resolveTaskQueueRouteContext,
  setTaskRouteContextFromRoute,
} = createWorkDetailSurface({
  addDaysIso,
  body,
  buildTaskProcessQualityFindings,
  cardPanel,
  cardPanelBody,
  cardPanelClose,
  cardPanelTitle,
  cardAnchorTone,
  escapeHtml,
  fetchResource: (url, options) => fetch(url, options),
  FOCUSABLE_SELECTOR:
    'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
  formatCardAnchorLabel,
  formatTaskDateMeta,
  getActiveTasksSection: () => workspaceState.activeTasksSection,
  getActiveWorkspaceRoute,
  getActiveWorkspaceRouteToken,
  getActiveWorkspaceView: () => workspaceState.activeWorkspaceView,
  getAllDocuments: () => knowledgeState.allDocuments,
  getCurrentOperator: () => getAccountIdentityState().user,
  hasApprovedArtifactEvidence,
  hasTaskFileEvidence,
  isArchivedWorkCard,
  isWorkspaceRouteFresh,
  labelizeWorkValue,
  localDocPathFromHref,
  navigateCanonicalWorkspace,
  openDocument,
  openQualityFinding,
  parseWorkspaceHash,
  promptUser: (message, initialValue) => window.prompt(message, initialValue),
  refreshDocuments,
  refreshOperationsWorkSnapshot,
  refreshWorkBell,
  renderEntityLoadState,
  renderTasksSurface: (documents, section) =>
    renderTasksSurface(documents, section),
  request,
  resolveDocReference,
  scheduleAnimationFrame: (callback) => requestAnimationFrame(callback),
  settledPayload,
  showUndoToast,
  state: workDetailState,
  summarizeCardProgress,
  taskDate,
  taskPanel,
  taskPanelBody,
  taskPanelClose,
  taskPanelTitle,
  taskProofState,
  taskRequiresApprovedArtifact,
  tasksFromWorkPayload,
  todayIsoDate,
  workApiUrl,
  workCardTitle,
  workTaskTitle,
  workflowTaskGroups,
});
taskPanelClose.addEventListener("click", closeTaskPanel);
taskModalBackdrop.addEventListener("click", closeTaskPanel);
cardPanelClose.addEventListener("click", closeCardPanel);
cardModalBackdrop?.addEventListener("click", closeCardPanel);
document.addEventListener("keydown", handleWorkspaceEntityModalKeydown);
const {
  openQuickTaskForm,
  openQuickWorkflowForm,
  recurringConfigTitle,
  refreshRuntimeTemplates,
  renderTasksSurface,
  resolveTemplateRouteEntity,
  setRuntimeTemplateRoute,
} = createTasksSurface({
  addBeforeUnloadListener: (listener) =>
    window.addEventListener("beforeunload", listener),
  allWorkTasks,
  buildOperationsWorkModel,
  cardsHeaderViewModel,
  compareIsoDate,
  confirmDialog,
  countLabel,
  debounce,
  describeRecurringRun,
  documentList,
  escapeHtml,
  formatTaskDateMeta,
  getActiveTasksSection: () => workspaceState.activeTasksSection,
  getActiveWorkspaceRoute,
  getActiveWorkspaceRouteToken,
  getAllDocuments: () => knowledgeState.allDocuments,
  getPendingLegacyRoute,
  getTaskRouteContext,
  getWorkspaceEntityState,
  groupCardItemsByMonth,
  groupCardItemsByStage,
  isArchivedWorkCard,
  isFollowUpDueTask,
  isOpenWorkTask,
  isOperationsWorkspaceVisible,
  isTaskDueToday,
  isTaskOverdue,
  isWaitingOrFollowUpTask,
  isWorkspaceRouteFresh,
  listDraftPaths,
  navigateCanonicalWorkspace,
  openDocument,
  openCardPanel,
  openTaskPanel,
  operationItemFromCard,
  referenceCountLabel,
  refreshDocuments,
  refreshOperationsRecurringSnapshot,
  refreshOperationsWorkSnapshot,
  renderAssistantsSurface: (...args) => renderAssistantsSurface(...args),
  renderEntityLoadState,
  renderHonestState,
  renderOperationsRuntimeState,
  renderSurfaceHeader,
  resolveAssigneeLabel,
  request,
  scheduleAnimationFrame: (callback) => requestAnimationFrame(callback),
  setRouteTitle,
  setWorkspaceEntityState,
  shellBody: body,
  sortWorkTasks,
  state: tasksSurfaceState,
  surfaceDescription,
  summarizeCardProgress,
  taskDate,
  taskNextActionLabel,
  taskProofState,
  taskSourceLabel,
  tasksSectionTitle,
  tasksFromWorkPayload,
  todayIsoDate,
  workApiUrl,
  workCardTitle,
  workTaskTitle,
});

const {
  refreshOperationsAssistantSnapshot,
  renderAssistantsSurface, renderDeviceSurfaceView,
} = createOperationsSurface({
  assistantJobsFromPayload,
  cssEscape: (value) => CSS.escape(value),
  dedupeArtifacts,
  defaultNextFollowUpDate,
  documentList,
  escapeHtml,
  formatTaskDateMeta,
  getActiveWorkspaceRoute,
  getActiveWorkspaceRouteToken,
  getActiveWorkspaceView: () => workspaceState.activeWorkspaceView,
  isMobileShell,
  isOperationsWorkspaceVisible,
  isWorkspaceRouteFresh,
  navigateCanonicalWorkspace,
  openCardPanel,
  openTaskPanel,
  promptUser: (message) => window.prompt(message),
  refreshDocuments,
  renderEntityLoadState,
  renderHonestState,
  renderSurfaceHeader,
  request,
  scheduleAnimationFrame: (callback) => requestAnimationFrame(callback),
  setRouteTitle,
  state: operationsSurfaceState,
  tasksFromWorkPayload,
  todayIsoDate,
  workApiUrl,
  workTaskTitle,
});

const customSelects = [];

reviewSurface = createReviewSurface({
  apiUrl,
  documentList,
  getActiveWorkspaceRoute,
  getActiveWorkspaceView: () => workspaceState.activeWorkspaceView,
  getDocsAvailability: () => workspaceState.docsSnapshot,
  navigateCanonicalWorkspace,
  openDocument,
  refreshDocuments,
  renderHonestState,
  request,
  reviewState: reviewSurfaceState,
  setRouteTitle,
});

knowledgeSurface = createKnowledgeSurface({
  apiUrl,
  assistantJobsFromPayload,
  basename,
  beginDocumentNavigation,
  buildOperationsWorkModel,
  buildOperationsReferenceLinks,
  buildProcessQualityModel,
  cardsFromWorkPayload,
  canLeaveCurrentDocument,
  cleanPath,
  closeSidebar,
  closeWorkBellPanel,
  confirmDialog,
  customSelects,
  diffBody,
  diffClose,
  diffModal,
  diffTitle,
  docContextReturn,
  docMenuButton,
  docState,
  documentList,
  documentPath,
  documentRowTemplate,
  documentState,
  documentTitle,
  draftKey: (...args) => documentEditorSurface.draftKey(...args),
  domainFilter,
  editor,
  editorView,
  emptyNote: (...args) => emptyNote(...args),
  enterRenderedMode: (...args) => enterRenderedMode(...args),
  escapeRegex,
  filterCount,
  knowledgeState,
  getActiveWorkspaceRoute,
  getActiveTasksSection: () => workspaceState.activeTasksSection,
  getActiveWorkspaceView: () => workspaceState.activeWorkspaceView,
  getDocsAvailability: () => workspaceState.docsSnapshot,
  getOperationsQualitySnapshot: () => workspaceState.qualitySnapshot,
  getOperationsRecurringSnapshot: () => workspaceState.recurringSnapshot,
  getOperationsWorkSnapshot: () => workspaceState.workSnapshot,
  labelizeWorkValue,
  listDraftPaths: (...args) => listDraftPaths(...args),
  navigateCanonicalWorkspace,
  openCardPanel,
  openQuickWorkflowForm,
  openTaskPanel,
  qualityFiltersState,
  operationsViewTitle,
  quickNav,
  quickNavInput,
  quickNavResults,
  renderedView,
  refreshChangesPanel: (...args) => refreshChangesPanel(...args),
  refreshKnowledgeStatus: (...args) => refreshKnowledgeStatus(...args),
  refreshOperationsAssistantSnapshot,
  refreshOperationsQualitySnapshot,
  refreshOperationsRecurringSnapshot,
  refreshOperationsWorkSnapshot,
  renameCurrentDoc: (...args) => renameCurrentDoc(...args),
  deleteCurrentDoc: (...args) => deleteCurrentDoc(...args),
  renderDocsAvailabilityState,
  renderHonestState,
  renderOperationsReference,
  renderOperationsWorkspace,
  renderQualityFindingRow,
  renderSurfaceHeader,
  request,
  resetCardPanel,
  resetTaskPanel,
  resizeDocumentTitle: (...args) => resizeDocumentTitle(...args),
  searchInput,
  setDocsAvailability: (snapshot) => { workspaceState.docsSnapshot = snapshot; },
  setRouteTitle,
  setSaveState: (...args) => setSaveState(...args),
  setView,
  showCreate,
  showWorkspaceSurface,
  surfaceDescription,
  systemFilter,
  tagFilter,
  tasksFromWorkPayload,
  titleFromMarkdown: (...args) => titleFromMarkdown(...args),
  typeFilter,
  updateSaveState: (...args) => updateSaveState(...args),
  updateViewToggleAvailability: (...args) =>
    updateViewToggleAvailability(...args),
  workApiUrl,
  scheduleAnimationFrame: (callback) => requestAnimationFrame(callback),
  locationAdapter: window.location,
  historyAdapter: history,
  promptUser: (message, initialValue) => window.prompt(message, initialValue),
  storage: localStorage,
  viewportWidth: () => window.innerWidth,
  body,
});
surfaceBridge.setKnowledgeSurface(knowledgeSurface);

documentEditorSurface = createDocumentEditor({
  beginDocumentNavigation,
  apiUrl,
  basename,
  body,
  canLeaveCurrentDocument,
  changesCount,
  changesDiscardAll,
  changesList,
  changesSaveAll,
  changesSection,
  changesStatus,
  cleanPath,
  closeSidebar,
  closeWorkBellPanel,
  confirmDialog,
  diffBody,
  diffModal,
  diffTitle,
  docMenuButton,
  documentPath,
  documentState,
  documentTitle,
  editor,
  editorDiscardButton,
  editorInlineStatus,
  editorSaveButton,
  editorSaveState,
  editorView,
  escapeHtml,
  historyPath, historySearchForm, historyStatus, historyVersions, historyComparison,
  historyButton,
  historyClose,
  historyModal,
  knowledgeStatusButton,
  knowledgeSection,
  knowledgeStatusText,
  getActiveWorkspaceRouteToken,
  isWorkspaceRouteFresh,
  knowledgeState,
  labelForPath: (...args) => labelForPath(...args),
  lightbox,
  lightboxCaption,
  lightboxImg,
  lintModal,
  lintModalBody,
  lintOpenButton,
  lintSummary,
  loadDocuments: (...args) => loadDocuments(...args),
  newDocPath,
  newDocForm,
  newDocSummary,
  newDocTitle,
  newDocType,
  openDocument: (...args) => openDocument(...args),
  openHistory: (...args) => openHistory(...args),
  operationsViewTitle,
  fetchBacklinksForCurrentDoc: (...args) =>
    knowledgeSurface.fetchBacklinksForCurrentDoc(...args),
  refreshDocuments: (...args) => refreshDocuments(...args),
  renderLoomBlock: (...args) => knowledgeSurface.renderLoomBlock(...args),
  renderRelatedDocsBlock: (...args) =>
    knowledgeSurface.renderRelatedDocsBlock(...args),
  renderWarningsBlock: (...args) =>
    knowledgeSurface.renderWarningsBlock(...args),
  renderedView,
  request,
  resetCardPanel,
  resetTaskPanel,
  resolveDocReference: (...args) => resolveDocReference(...args),
  resolveMarkdownDocLink: (...args) => resolveMarkdownDocLink(...args),
  searchInput,
  setFolderUrl: (...args) => setFolderUrl(...args),
  setRouteTitle,
  setView,
  showLibrary: (...args) => showLibrary(...args),
  showUndoToast,
  viewToggleButton,
  visibleDocUrl: (...args) => visibleDocUrl(...args),
  scheduleAnimationFrame: (callback) => requestAnimationFrame(callback),
  storage: localStorage,
  promptUser: (message, initialValue) => window.prompt(message, initialValue),
});
surfaceBridge.setDocumentEditorSurface(documentEditorSurface);

navigationShell = createNavigationShell({
  canLeaveCurrentDocument,
  canonicalWorkspaceUrl,
  clearDocumentFilters,
  closeSettingsMenu,
  closeSidebar,
  closeWorkBellPanel,
  docPathFromLocation,
  documentList,
  documentRef: document,
  folderExists,
  folderPathFromLocation,
  getAssistantQueueState: () => workspaceState.assistantQueue,
  getDocsAvailability: () => workspaceState.docsSnapshot,
  getKnowledgeState: () => knowledgeState,
  getTasksSectionForLegacyView: legacyViewToTasksSection,
  historyRef: history,
  HTMLElementClass: HTMLElement,
  hydrateCardPanel,
  hydrateTaskPanel,
  locationRef: window.location,
  openDocument,
  openWorkBellPanel,
  operationsViewTitle,
  parseWorkspaceHash,
  prepareCardPanel,
  prepareTaskPanel,
  refreshDocuments,
  refreshOperationsAssistantSnapshot,
  refreshReviewSnapshot: (...args) => reviewSurface.refreshReviewSnapshot(...args),
  refreshUsersSurface,
  refreshWorkBell,
  restoreDocumentFilters,
  renderWorkspaceNav: () => {
    syncWorkspaceNav();
    return {
      activeWorkspaceView: workspaceState.activeWorkspaceView,
      activeTasksSection: workspaceState.activeTasksSection,
    };
  },
  requestAnimationFrameImpl: requestAnimationFrame,
  resetCardPanel,
  resetTaskPanel,
  resolveTaskQueueRouteContext,
  resolveTemplateRouteEntity,
  searchInput,
  setActiveTasksSection: (section) => {
    workspaceState.activeTasksSection = section;
  },
  setActiveWorkspaceView: (view) => {
    workspaceState.activeWorkspaceView = view;
  },
  setRuntimeTemplateRoute,
  setTaskRouteContextFromRoute,
  setView,
  showLibrary,
  workspaceRouteFor,
});
surfaceBridge.setNavigationShell(navigationShell);
bindApplicationEvents({
  callbacks: {
    closeCardPanel,
    closeHistory,
    closeCustomSelects,
    closeDiff,
    closeLightbox,
    closeQuickNav,
    closeSettingsMenu,
    closeSidebar,
    closeTaskPanel,
    closeWorkBellPanel,
    createDocument,
    debounce,
    discardAllDrafts,
    discardDraft,
    handleClipboardPaste,
    handleWorkspaceEntityModalKeydown,
    isSettingsMenuOpen,
    navigateCanonicalWorkspace,
    onFilterChange,
    openHistory,
    openDocMenu,
    openLintReport,
    openQuickNav,
    openSidebar,
    refreshDocuments,
    refreshKnowledgeStatus,
    clearDocumentFilters,
    resizeDocumentTitle,
    saveAllDrafts,
    saveCurrentDocument,
    setDarkMode,
    setSidebarCollapsed,
    showCreate,
    showLibrary,
    showWorkspaceSurface,
    storeDraft,
    syncSidebarShellState,
    syncTitleToMarkdown,
    toggleViewMode,
    updateQuickNavMatches,
    updateSaveState,
    workspaceHashPath,
  },
  documentRef: document,
  dom,
  navigationShell,
  notificationsShell,
  surfaceBridge,
  windowRef: window,
  workspaceState,
});


initializeAppShell({
  enhanceSelect,
  filterSelects: [
    domainFilter,
    typeFilter,
    systemFilter,
    tagFilter,
    newDocType,
  ],
  loadDocuments,
  navigationShell,
  refreshChangesPanel,
  refreshKnowledgeStatus,
  refreshOperationsWorkSnapshot,
  restoreDarkMode,
  restoreSidebarCollapsed,
  showLibrary,
  syncSidebarShellState,
  updateSaveState,
  windowRef: window,
});

// Refresh "Saved · 2 min ago" every minute so the relative time stays current.
setInterval(() => {
  if (
    documentState.currentDoc &&
    editor.value === documentState.lastSavedContent
  ) {
    updateSaveState();
  }
}, 60000);
