export function applicationRuntimeLoaded() {
  return true;
}

import {
  addDaysIso, buildHomeAttentionItems, canonicalWorkspaceUrl,
  cardsHeaderViewModel, compareIsoDate, dedupeWorkTasks,
  deriveHomeWorkState, formatHomeCalendarDate, formatHomeShortDate,
  formatHomeTaskTiming, formatTaskDateMeta, groupCardItemsByStage,
  hasApprovedArtifactEvidence, hasTaskFileEvidence, isActiveWorkBundle,
  isArchivedWorkBundle, isBeforeIsoDate, isFollowUpDueTask,
  isOpenWorkTask, isTaskDueToday, isTaskOverdue,
  isWaitingOrFollowUpTask, isoDayDistance, parseWorkspaceHash,
  summarizeBundleProgress, taskDate, taskProofState,
  taskRequiresApprovedArtifact, tasksFromWorkPayload, tasksSectionTitle,
  todayIsoDate, workBundleTitle, workTaskTitle, workflowTaskGroups,
  workspaceHashPath, workspaceRouteFor,
} from "../core/workspace.js";
import {
  assistantJobsFromPayload, bundlesFromWorkPayload,
  currentOperatorIdFromPayload, emptyOperationsArtifactSnapshot,
  emptyOperationsAssistantSnapshot, emptyOperationsQualitySnapshot,
  emptyOperationsRecurringSnapshot, emptyOperationsWorkSnapshot,
  labelizeWorkValue, normalizeTemplateMatchValue,
  recurringConfigsFromPayload, settledPayload, usersFromWorkPayload,
} from "../core/operations-model.js";
import { createFinanceSurface } from "../surfaces/finance/index.js";
import { createHomeSurface } from "../surfaces/home.js";
import { createAdminSurface, createOperationsSurface } from "../surfaces/operations/index.js";
import { createPlanningSurface } from "../surfaces/planning.js";
import { createTasksSurface } from "../surfaces/tasks/index.js";
import { createWorkDetailSurface } from "../surfaces/work-detail/index.js";
import { createKnowledgeSurface } from "../surfaces/knowledge/index.js";
import { createDocumentEditor } from "../surfaces/document-editor/index.js";
import { createApiClient, resolveApiBase } from "../shell/api.js";
import { createFeedbackShell } from "../shell/feedback.js";
import { createNavigationShell } from "../shell/navigation.js";
import { initializeAppShell } from "../shell/bootstrap.js";
import { queryAppDom } from "../shell/dom-bindings.js";
import { bindApplicationEvents } from "./application-events.js";
import { createOperationKernel } from "./operation-kernel.js";
import { createApplicationShells } from "./shell-composition.js";
import { createWorkspaceState } from "../runtime/workspace-state.js";
import { createSurfaceBridge, createSurfaceComposition } from "./surface-composition.js";
let knowledgeSurface;
let documentEditorSurface;
let navigationShell;

const surfaceBridge = createSurfaceBridge();
const {
  applyWorkspaceRoute, beginDocumentNavigation, canLeaveDocumentEditor, closeCustomSelects, clearDocumentFilters, clearSelection,
  closeDiff, closeLightbox, closeQuickNav, createDocument, deleteCurrentDoc, discardAllDrafts, discardDraft, docPathFromLocation,
  emptyNote, enhanceSelect, enterRenderedMode, escapeRegex, folderExists, folderPathFromLocation, getActiveWorkspaceRoute,
  getActiveWorkspaceRouteToken, getPendingLegacyRoute, getWorkspaceEntityState, handleClipboardPaste, humanizeOptionLabel,
  isWorkspaceRouteFresh, labelForPath, listDraftPaths, loadDocuments, localDocPathFromHref, navigateCanonicalWorkspace,
  onFilterChange, openCommitForm, openDocMenu, openDocument, openLintReport, openQuickNav, populateFilterOptions,
  refreshChangesPanel, refreshDocuments, refreshGitStatus, renameCurrentDoc, renderDocsSurface, renderProcessesSurface,
  renderUnifiedSearchSurface, resolveDocReference, resolveMarkdownDocLink, restoreFiltersExpanded, saveAllDrafts,
  saveCurrentDocument, setFiltersExpanded, setFolderUrl, setSaveState, setWorkspaceEntityState, showCreate, showLibrary,
  storeDraft, submitCommitForm, syncLibraryPageTitle, syncTitleToMarkdown, titleFromMarkdown, toggleCurrentDocPin,
  toggleViewMode, updateCustomSelect, updateFilterSummary, updateGithubLink, updateQuickNavMatches, updateSaveState,
  updateViewToggleAvailability, visibleDocUrl, gitPull, closeCommitForm, resizeDocumentTitle,
} = surfaceBridge;
const API_BASE = resolveApiBase({ documentRef: document, windowRef: window });
const { apiUrl, request } = createApiClient({
  apiBase: API_BASE,
  fetchImpl: (...args) => fetch(...args),
  storage: localStorage,
});
const workspaceState = createWorkspaceState({
  emptyOperationsArtifactSnapshot,
  emptyOperationsAssistantSnapshot,
  emptyOperationsQualitySnapshot,
  emptyOperationsRecurringSnapshot,
  emptyOperationsWorkSnapshot,
  getAccountIdentityState: () => getAccountIdentityState(),
  getWorkspaceEntityState,
  setWorkspaceEntityState,
});
const {
  documentState,
  homeSurfaceState,
  knowledgeState,
  operationsSurfaceState,
  overviewState,
  qualityFiltersState,
  tasksSurfaceState,
  workDetailState,
} = workspaceState;

const dom = queryAppDom(document);
const {
  body, sidebar, sidebarScrim, sidebarResize, mobileMenuButton,
  sidebarCloseButton, sidebarCollapseButton, themeToggleButton,
  sidebarExpandButton, changesSection, changesToggle, changesCount,
  changesList, changesSaveAll, changesDiscardAll, lintOpenButton,
  lintSummary, lintModal, lintBackdrop, lintModalBody, lintModalClose,
  gitSection, gitStatusText, gitCommitButton, gitPullButton, gitCommitModal,
  gitCommitBackdrop, gitCommitForm, gitCommitFiles, gitCommitMessage,
  gitCommitCancel, gitCommitSubmit, gitResult, mobileNewButton,
  operationsHomeButton, newDocumentButton, searchForm, searchInput,
  domainFilter, typeFilter, systemFilter, tagFilter, filterToggle,
  filtersSection, filterCount, filterRow, docTree, recentList,
  recentlyViewedSection, recentlyViewedList, helpModal, helpClose,
  documentList, pageShell, documentRowTemplate, breadcrumb, toolbarTitle,
  mobileTitle, statusText, libraryTitle, clearSelectionButton, backButton,
  saveState, discardButton, saveButton, documentTitle, documentPath,
  editor, editorView, renderedView, viewToggleButton, docMenuButton,
  docPinButton, pinnedSection, pinnedList, newDocForm, newDocPath,
  newDocTitle, newDocType, newDocSummary, workspaceNavButtons,
  tasksNavButton, tasksNavSubmenu, tasksNavSectionButtons, docContextReturn,
  taskPanel, taskPanelTitle, taskPanelBody, taskPanelClose, taskModalBackdrop,
  bundlePanel, bundlePanelTitle, bundlePanelBody, bundlePanelClose,
  bundleModalBackdrop, diffModal, diffTitle, diffBody, lightbox,
  lightboxImg, lightboxCaption, quickNav, quickNavInput, quickNavResults,
} = dom;
const {
  allWorkTasks,
  basename,
  canLeaveCurrentDocument,
  cleanPath,
  debounce,
  escapeHtml,
  isOperationsHomeVisible,
  legacyViewToTasksSection,
  refreshOperationsRecurringSnapshot,
  renderOperationsWorkspace,
  setPageTitle,
  setStatus,
  setTasksNavExpanded,
  setView,
  showOperationsHome,
  showWorkspaceSurface,
  syncWorkspaceNav,
  workApiUrl,
} = createSurfaceComposition({
  apiUrl,
  body,
  breadcrumb,
  clearTimeoutImpl: clearTimeout,
  dedupeWorkTasks,
  emptyOperationsRecurringSnapshot,
  getCanLeaveDocumentEditor: () => canLeaveDocumentEditor,
  getCanLeaveFinanceSurface: () => canLeaveFinanceSurface,
  getConfirmLeaveRuntimeDraft: () => confirmLeaveRuntimeDraft,
  getKnowledgeSelectedFolder: () => knowledgeState.selectedFolder,
  getNormalizeOperationsRecurringSnapshot: () =>
    normalizeOperationsRecurringSnapshot,
  getRenderAdminSurfaceView: () => renderAdminSurfaceView,
  getRenderBookkeepingSurface: () => renderBookkeepingSurface,
  getRenderCalendarSurface: () => renderCalendarSurface,
  getRenderDocsSurface: () => renderDocsSurface,
  getRenderInboxSurface: () => renderInboxSurface,
  getRenderMailingExportsSurface: () => renderMailingExportsSurface,
  getRenderNewsletterSurface: () => renderNewsletterSurface,
  getRenderOperationsHome: () => renderOperationsHome,
  getRenderSponsorCrmSurface: () => renderSponsorCrmSurface,
  getRenderTasksSurface: () => renderTasksSurface,
  getRenderUsersSurfaceView: () => renderUsersSurfaceView,
  getResizeDocumentTitle: () => resizeDocumentTitle,
  getSearchValue: () => searchInput.value,
  isOpenWorkTask,
  mobileTitle,
  navigateCanonicalWorkspace,
  recurringConfigsFromPayload,
  refreshDocuments,
  request,
  searchInput,
  setTimeoutImpl: setTimeout,
  statusText,
  tasksFromWorkPayload,
  tasksNavButton,
  tasksNavSectionButtons,
  tasksNavSubmenu,
  toolbarTitle,
  windowConsole: console,
  workspaceHashPath,
  workspaceNavButtons,
  workspaceState,
});
const {
  confirmDialog,
  renderEntityLoadState,
  renderEntityLoadingState,
  reportError,
  showErrorToast,
  showUndoToast,
} = createFeedbackShell({
  clearTimeoutImpl: clearTimeout,
  documentRef: document,
  HTMLElementClass: HTMLElement,
  labelizeWorkValue,
  requestAnimationFrameImpl: requestAnimationFrame,
  setStatus,
  setTimeoutImpl: setTimeout,
});
const {
  canLeaveFinanceSurface,
  renderBookkeepingSurface,
  renderMailingExportsSurface,
  renderSponsorCrmSurface,
} = createFinanceSurface({
  documentList,
  escapeHtml,
  formatTaskDateMeta,
  getPendingLegacyRoute,
  humanizeOptionLabel,
  isWorkspaceRouteFresh,
  navigateCanonicalWorkspace,
  request,
  renderEntityLoadState,
  setPageTitle,
  workApiUrl,
});
const { renderCalendarSurface, renderNewsletterSurface } =
  createPlanningSurface({
    documentList,
    escapeHtml,
    request,
    setPageTitle,
    workApiUrl,
  });
const {
  account: {
    activeWorkOwner, activeWorkOwnerId, closeSettingsMenu,
    currentOperatorFromPayload, getAccountIdentityState,
    isSettingsMenuOpen, readLocalPreviewContext, refreshAccountIdentity,
  },
  notifications: notificationsShell,
  preferences: {
    attachSidebarResize, closeSidebar, isMobileShell, openSidebar,
    restoreDarkMode, restoreSidebarCollapsed, restoreSidebarWidth,
    setDarkMode, setSidebarCollapsed, syncSidebarShellState,
    syncThemeToggleLabel,
  },
} = createApplicationShells({
  canLeaveCurrentDocument,
  documentRef: document,
  dom,
  fetchImpl: (...args) => fetch(...args),
  formatHomeShortDate,
  formatTaskDateMeta,
  HTMLElementClass: HTMLElement,
  isOperationsHomeVisible,
  isWorkspaceRouteFresh,
  isoDayDistance,
  localStorageRef: localStorage,
  navigateCanonicalWorkspace,
  openTaskPanel: (...args) => openTaskPanel(...args),
  parseWorkspaceHash,
  refreshDocuments,
  request,
  showWorkspaceSurface,
  todayIsoDate,
  windowRef: window,
  workApiUrl,
  workspaceState,
});
const {
  closeWorkBellPanel, openWorkBellPanel, refreshWorkBell,
} = notificationsShell;

const {
  buildOperationsFutureSections,
  buildOperationsReferenceLinks,
  currentOperatorIdForTodayScope,
  dedupeOperationItems,
  isAtRiskWorkflowSlug,
  isCurrentOperatorTodayTask,
  isFollowUpDoc,
  isRecurringWorkflowSlug,
  isSyntheticCurrentOperatorId,
  isTaskAssignedTo,
  isWorkflowTemplateDoc,
  normalizeBundleTaskMap,
  normalizeOperationsRecurringSnapshot,
  normalizeOperationsWorkSnapshot,
  operationItemFromBundle,
  operationItemFromDoc,
  operationItemFromTask,
  operationItemFromTemplate,
  countLabel,
  openQualityFinding,
  operationsViewPath,
  operationsViewTitle,
  referenceCountLabel,
  renderHonestState,
  renderOperationalSurfaceStates,
  renderOperationsFutureSections,
  renderOperationsLane,
  renderOperationsReference,
  renderOperationsRuntimeState,
  renderProcessQualityHomeSection,
  renderQualityFindingRow,
  renderSurfaceHeader,
  surfaceDescription,
  surfaceStatusText,
  sortActiveWorkBundles,
  sortWorkTasks,
  summarizeWorkflowTemplate,
  taskNextActionLabel,
  taskSortDate,
  taskSourceLabel,
  workflowPriority,
  workflowSlugFromDoc,
} = createOperationKernel({
  basename,
  cleanPath,
  documentRef: document,
  getRecurringConfigTitle: (...args) => recurringConfigTitle(...args),
  openBundlePanel: (...args) => openBundlePanel(...args),
  openDocument: (...args) => openDocument(...args),
  openTaskPanel: (...args) => openTaskPanel(...args),
  resolveAssigneeLabel: (...args) => resolveAssigneeLabel(...args),
  resolveDocReference: (...args) => resolveDocReference(...args),
  showWorkspaceSurface: (...args) => showWorkspaceSurface(...args),
  tasksSectionTitle,
  workspaceState,
});
const {
  buildNeedsActionLane,
  buildOperationsHomeModel,
  buildProcessQualityModel,
  buildTaskProcessQualityFindings,
  refreshOperationsQualitySnapshot,
  refreshOperationsWorkSnapshot,
  renderOperationsHome,
} = createHomeSurface({
  activeWorkOwner,
  activeWorkOwnerId,
  addDaysIso,
  allWorkTasks,
  buildHomeAttentionItems,
  buildOperationsFutureSections,
  buildOperationsReferenceLinks,
  bundlesFromWorkPayload,
  clearSelectionButton,
  currentOperatorIdForTodayScope,
  currentOperatorIdFromPayload,
  dedupeOperationItems,
  deriveHomeWorkState,
  documentList,
  emptyOperationsQualitySnapshot,
  emptyOperationsWorkSnapshot,
  formatHomeCalendarDate,
  formatHomeTaskTiming,
  isActiveWorkBundle,
  isOpenWorkTask,
  isOperationsHomeVisible,
  isWorkflowTemplateDoc,
  isWorkspaceRouteFresh,
  libraryTitle,
  listDraftPaths,
  navigateCanonicalWorkspace,
  normalizeOperationsRecurringSnapshot,
  normalizeOperationsWorkSnapshot,
  normalizeTemplateMatchValue,
  openQuickTaskForm: (...args) => openQuickTaskForm(...args),
  openQuickWorkflowForm: (...args) => openQuickWorkflowForm(...args),
  openTaskPanel: (...args) => openTaskPanel(...args),
  operationItemFromBundle,
  operationItemFromTask,
  operationItemFromTemplate,
  readLocalPreviewContext,
  refreshAccountIdentity,
  refreshDocuments,
  refreshWorkBell,
  renderHonestState,
  renderOperationsRuntimeState,
  request,
  resolveBundleLabel: (...args) => resolveBundleLabel(...args),
  resolveDocReference,
  setPageTitle,
  setStatus,
  settledPayload,
  state: homeSurfaceState,
  summarizeWorkflowTemplate,
  tasksFromWorkPayload,
  todayIsoDate,
  usersFromWorkPayload,
  workApiUrl,
  workBundleTitle,
  workTaskTitle,
  workflowPriority,
});
const {
  refreshUsersSurface,
  renderAdminSurface,
  renderAdminSurfaceView,
  renderUsersSurfaceView,
} = createAdminSurface({
  apiUrl,
  buildOperationsHomeModel,
  clearSelectionButton,
  currentOperatorIdFromPayload,
  documentList,
  getActiveWorkspaceView: () => workspaceState.activeWorkspaceView,
  getOperationsQualitySnapshot: () => workspaceState.qualitySnapshot,
  getOperationsRecurringSnapshot: () => workspaceState.recurringSnapshot,
  getOperationsWorkSnapshot: () => workspaceState.workSnapshot,
  libraryTitle,
  listDraftPaths,
  refreshDocuments,
  renderHonestState,
  renderSurfaceHeader,
  request,
  setPageTitle,
  setStatus,
  settledPayload,
  showCreate,
  showErrorToast,
  showWorkspaceSurface,
  surfaceDescription,
  surfaceStatusText,
  usersFromWorkPayload,
  workApiUrl,
});
const {
  closeBundlePanel,
  closeTaskPanel,
  dedupeArtifacts,
  defaultNextFollowUpDate,
  getTaskRouteContext,
  handleWorkspaceEntityModalKeydown,
  hydrateBundlePanel,
  hydrateTaskPanel,
  openBundlePanel,
  openTaskPanel,
  prepareBundlePanel,
  prepareTaskPanel,
  renderArtifactList,
  resetBundlePanel,
  resetTaskPanel,
  resolveAssigneeLabel,
  resolveBundleLabel,
  resolveTaskQueueRouteContext,
  setTaskRouteContextFromRoute,
} = createWorkDetailSurface({
  addDaysIso,
  body,
  buildTaskProcessQualityFindings,
  bundlePanel,
  bundlePanelBody,
  bundlePanelClose,
  bundlePanelTitle,
  escapeHtml,
  fetchResource: (url, options) => fetch(url, options),
  FOCUSABLE_SELECTOR:
    'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
  formatTaskDateMeta,
  getActiveTasksSection: () => workspaceState.activeTasksSection,
  getActiveWorkspaceRoute,
  getActiveWorkspaceRouteToken,
  getActiveWorkspaceView: () => workspaceState.activeWorkspaceView,
  getAllDocuments: () => knowledgeState.allDocuments,
  getCurrentOperator: () => getAccountIdentityState().user,
  hasApprovedArtifactEvidence,
  hasTaskFileEvidence,
  isArchivedWorkBundle,
  isWorkspaceRouteFresh,
  labelizeWorkValue,
  localDocPathFromHref,
  navigateCanonicalWorkspace,
  openDocument,
  openQualityFinding,
  parseWorkspaceHash,
  promptUser: (message, initialValue) => window.prompt(message, initialValue),
  refreshDocuments,
  refreshOperationsWorkSnapshot,
  refreshWorkBell,
  renderEntityLoadState,
  renderTasksSurface: (documents, section) =>
    renderTasksSurface(documents, section),
  reportError,
  request,
  resolveDocReference,
  scheduleAnimationFrame: (callback) => requestAnimationFrame(callback),
  setStatus,
  settledPayload,
  showUndoToast,
  state: workDetailState,
  summarizeBundleProgress,
  taskDate,
  taskPanel,
  taskPanelBody,
  taskPanelClose,
  taskPanelTitle,
  taskProofState,
  taskRequiresApprovedArtifact,
  tasksFromWorkPayload,
  todayIsoDate,
  workApiUrl,
  workBundleTitle,
  workTaskTitle,
  workflowTaskGroups,
});
taskPanelClose.addEventListener("click", closeTaskPanel);
taskModalBackdrop.addEventListener("click", closeTaskPanel);
bundlePanelClose.addEventListener("click", closeBundlePanel);
bundleModalBackdrop?.addEventListener("click", closeBundlePanel);
document.addEventListener("keydown", handleWorkspaceEntityModalKeydown);
const {
  confirmLeaveRuntimeDraft,
  openQuickTaskForm,
  openQuickWorkflowForm,
  recurringConfigTitle,
  refreshRuntimeTemplates,
  renderTasksSurface,
  resolveTemplateRouteEntity,
  setRuntimeTemplateRoute,
} = createTasksSurface({
  addBeforeUnloadListener: (listener) =>
    window.addEventListener("beforeunload", listener),
  allWorkTasks,
  buildOperationsHomeModel,
  cardsHeaderViewModel,
  clearSelectionButton,
  compareIsoDate,
  confirmDialog,
  countLabel,
  debounce,
  documentList,
  escapeHtml,
  formatTaskDateMeta,
  getActiveTasksSection: () => workspaceState.activeTasksSection,
  getActiveWorkspaceRoute,
  getActiveWorkspaceRouteToken,
  getAllDocuments: () => knowledgeState.allDocuments,
  getPendingLegacyRoute,
  getTaskRouteContext,
  getWorkspaceEntityState,
  groupCardItemsByStage,
  isArchivedWorkBundle,
  isFollowUpDueTask,
  isOpenWorkTask,
  isOperationsHomeVisible,
  isTaskDueToday,
  isTaskOverdue,
  isWaitingOrFollowUpTask,
  isWorkspaceRouteFresh,
  libraryTitle,
  listDraftPaths,
  navigateCanonicalWorkspace,
  openDocument,
  openBundlePanel,
  openTaskPanel,
  operationItemFromBundle,
  referenceCountLabel,
  refreshDocuments,
  refreshOperationsRecurringSnapshot,
  refreshOperationsWorkSnapshot,
  renderArtifactsSurface: (...args) => renderArtifactsSurface(...args),
  renderAssistantsSurface: (...args) => renderAssistantsSurface(...args),
  renderEntityLoadState,
  renderHonestState,
  renderOperationsRuntimeState,
  renderSurfaceHeader,
  reportError,
  resolveAssigneeLabel,
  request,
  scheduleAnimationFrame: (callback) => requestAnimationFrame(callback),
  setPageTitle,
  setStatus,
  setWorkspaceEntityState,
  shellBody: body,
  showErrorToast,
  sortWorkTasks,
  state: tasksSurfaceState,
  surfaceDescription,
  summarizeBundleProgress,
  taskDate,
  taskNextActionLabel,
  taskProofState,
  taskSourceLabel,
  tasksSectionTitle,
  tasksFromWorkPayload,
  todayIsoDate,
  workApiUrl,
  workBundleTitle,
  workTaskTitle,
});

const {
  refreshIntakeSnapshot,
  refreshOperationsArtifactSnapshot,
  refreshOperationsAssistantSnapshot,
  renderArtifactsSurface,
  renderAssistantsSurface,
  renderInboxSurface,
  resolveIntakeRouteEntity,
} = createOperationsSurface({
  assistantJobsFromPayload,
  clearSelectionButton,
  cssEscape: (value) => CSS.escape(value),
  dedupeArtifacts,
  defaultNextFollowUpDate,
  documentList,
  escapeHtml,
  getActiveWorkspaceRoute,
  getActiveWorkspaceView: () => workspaceState.activeWorkspaceView,
  isMobileShell,
  isOperationsHomeVisible,
  isWorkspaceRouteFresh,
  libraryTitle,
  navigateCanonicalWorkspace,
  openBundlePanel,
  openTaskPanel,
  promptUser: (message) => window.prompt(message),
  refreshDocuments,
  renderEntityLoadState,
  renderHonestState,
  reportError,
  request,
  scheduleAnimationFrame: (callback) => requestAnimationFrame(callback),
  setPageTitle,
  setStatus,
  showCreate,
  state: operationsSurfaceState,
  tasksFromWorkPayload,
  todayIsoDate,
  workApiUrl,
  workTaskTitle,
});

const customSelects = [];

knowledgeSurface = createKnowledgeSurface({
  apiUrl,
  assistantJobsFromPayload,
  basename,
  buildOperationsHomeModel,
  buildOperationsReferenceLinks,
  buildProcessQualityModel,
  bundlesFromWorkPayload,
  canLeaveCurrentDocument,
  cleanPath,
  clearSelectionButton,
  closeSidebar,
  closeWorkBellPanel,
  confirmDialog,
  customSelects,
  diffBody,
  diffModal,
  diffTitle,
  docContextReturn,
  docMenuButton,
  docPinButton,
  docTree,
  documentList,
  documentPath,
  documentRowTemplate,
  documentState,
  documentTitle,
  draftKey: (...args) => documentEditorSurface.draftKey(...args),
  domainFilter,
  editor,
  editorView,
  emptyNote: (...args) => emptyNote(...args),
  enterRenderedMode: (...args) => enterRenderedMode(...args),
  escapeRegex,
  filterCount,
  filterRow,
  filterToggle,
  filtersSection,
  knowledgeState,
  getActiveTasksSection: () => workspaceState.activeTasksSection,
  getActiveWorkspaceView: () => workspaceState.activeWorkspaceView,
  getOperationsQualitySnapshot: () => workspaceState.qualitySnapshot,
  getOperationsRecurringSnapshot: () => workspaceState.recurringSnapshot,
  getOperationsWorkSnapshot: () => workspaceState.workSnapshot,
  labelizeWorkValue,
  libraryTitle,
  listDraftPaths: (...args) => listDraftPaths(...args),
  navigateCanonicalWorkspace,
  openBundlePanel,
  openQuickWorkflowForm,
  openTaskPanel,
  qualityFiltersState,
  operationsViewPath,
  operationsViewTitle,
  pinnedList,
  pinnedSection,
  quickNav,
  quickNavInput,
  quickNavResults,
  recentList,
  recentlyViewedList,
  recentlyViewedSection,
  renderedView,
  refreshChangesPanel: (...args) => refreshChangesPanel(...args),
  refreshGitStatus: (...args) => refreshGitStatus(...args),
  refreshOperationsArtifactSnapshot,
  refreshOperationsAssistantSnapshot,
  refreshOperationsQualitySnapshot,
  refreshOperationsRecurringSnapshot,
  refreshOperationsWorkSnapshot,
  renameCurrentDoc: (...args) => renameCurrentDoc(...args),
  deleteCurrentDoc: (...args) => deleteCurrentDoc(...args),
  renderHonestState,
  renderOperationsReference,
  renderOperationsWorkspace,
  renderQualityFindingRow,
  renderSurfaceHeader,
  reportError,
  request,
  resetBundlePanel,
  resetTaskPanel,
  searchInput,
  setPageTitle,
  setSaveState: (...args) => setSaveState(...args),
  setStatus,
  setView,
  showOperationsHome,
  showWorkspaceSurface,
  surfaceDescription,
  surfaceStatusText,
  systemFilter,
  tagFilter,
  tasksFromWorkPayload,
  titleFromMarkdown: (...args) => titleFromMarkdown(...args),
  typeFilter,
  updateGithubLink: (...args) => updateGithubLink(...args),
  updateSaveState: (...args) => updateSaveState(...args),
  updateViewToggleAvailability: (...args) =>
    updateViewToggleAvailability(...args),
  workApiUrl,
  scheduleAnimationFrame: (callback) => requestAnimationFrame(callback),
  locationAdapter: window.location,
  historyAdapter: history,
  promptUser: (message, initialValue) => window.prompt(message, initialValue),
  storage: localStorage,
  viewportWidth: () => window.innerWidth,
  body,
});
surfaceBridge.setKnowledgeSurface(knowledgeSurface);

documentEditorSurface = createDocumentEditor({
  beginDocumentNavigation,
  apiUrl,
  basename,
  body,
  canLeaveCurrentDocument,
  changesCount,
  changesDiscardAll,
  changesList,
  changesSaveAll,
  changesSection,
  cleanPath,
  closeSidebar,
  closeWorkBellPanel,
  confirmDialog,
  diffBody,
  diffModal,
  diffTitle,
  discardButton,
  docMenuButton,
  docTree,
  documentPath,
  documentState,
  documentTitle,
  domainFilter,
  editor,
  editorView,
  escapeHtml,
  gitCommitButton,
  gitCommitCancel,
  gitCommitFiles,
  gitCommitMessage,
  gitCommitModal,
  gitCommitSubmit,
  gitPullButton,
  gitResult,
  gitSection,
  gitStatusText,
  knowledgeState,
  labelForPath: (...args) => labelForPath(...args),
  lightbox,
  lightboxCaption,
  lightboxImg,
  lintModal,
  lintModalBody,
  lintOpenButton,
  lintSummary,
  loadDocuments: (...args) => loadDocuments(...args),
  newDocPath,
  newDocForm,
  newDocSummary,
  newDocTitle,
  newDocType,
  openDocument: (...args) => openDocument(...args),
  operationsViewPath,
  operationsViewTitle,
  fetchBacklinksForCurrentDoc: (...args) =>
    knowledgeSurface.fetchBacklinksForCurrentDoc(...args),
  refreshDocuments: (...args) => refreshDocuments(...args),
  renderGithubRawFooter: (...args) =>
    knowledgeSurface.renderGithubRawFooter(...args),
  renderLoomBlock: (...args) => knowledgeSurface.renderLoomBlock(...args),
  renderRelatedDocsBlock: (...args) =>
    knowledgeSurface.renderRelatedDocsBlock(...args),
  renderWarningsBlock: (...args) =>
    knowledgeSurface.renderWarningsBlock(...args),
  renderedView,
  reportError,
  request,
  resetBundlePanel,
  resetTaskPanel,
  resolveDocReference: (...args) => resolveDocReference(...args),
  resolveMarkdownDocLink: (...args) => resolveMarkdownDocLink(...args),
  saveButton,
  saveState,
  searchInput,
  setFolderUrl: (...args) => setFolderUrl(...args),
  setPageTitle,
  setStatus,
  setView,
  showLibrary: (...args) => showLibrary(...args),
  showUndoToast,
  systemFilter,
  tagFilter,
  typeFilter,
  updateCustomSelect: (...args) => updateCustomSelect(...args),
  updateFilterSummary: (...args) => updateFilterSummary(...args),
  viewToggleButton,
  visibleDocUrl: (...args) => visibleDocUrl(...args),
  showErrorToast,
  scheduleAnimationFrame: (callback) => requestAnimationFrame(callback),
  storage: localStorage,
  promptUser: (message, initialValue) => window.prompt(message, initialValue),
});
surfaceBridge.setDocumentEditorSurface(documentEditorSurface);

navigationShell = createNavigationShell({
  canLeaveCurrentDocument,
  canonicalWorkspaceUrl,
  clearDocumentFilters,
  closeSettingsMenu,
  closeSidebar,
  closeWorkBellPanel,
  docPathFromLocation,
  documentList,
  documentRef: document,
  folderExists,
  folderPathFromLocation,
  getAssistantQueueState: () => workspaceState.assistantQueue,
  getIntakeState: () => workspaceState.intake,
  getKnowledgeState: () => knowledgeState,
  getTasksSectionForLegacyView: legacyViewToTasksSection,
  historyRef: history,
  HTMLElementClass: HTMLElement,
  hydrateBundlePanel,
  hydrateTaskPanel,
  libraryTitle,
  locationRef: window.location,
  openDocument,
  openWorkBellPanel,
  operationsViewTitle,
  parseWorkspaceHash,
  prepareBundlePanel,
  prepareTaskPanel,
  refreshDocuments,
  refreshOperationsArtifactSnapshot,
  refreshOperationsAssistantSnapshot,
  refreshUsersSurface,
  refreshWorkBell,
  renderWorkspaceNav: () => {
    syncWorkspaceNav();
    return {
      activeWorkspaceView: workspaceState.activeWorkspaceView,
      activeTasksSection: workspaceState.activeTasksSection,
    };
  },
  requestAnimationFrameImpl: requestAnimationFrame,
  resetBundlePanel,
  resetTaskPanel,
  resolveIntakeRouteEntity,
  resolveTaskQueueRouteContext,
  resolveTemplateRouteEntity,
  searchInput,
  setActiveTasksSection: (section) => {
    workspaceState.activeTasksSection = section;
  },
  setActiveWorkspaceView: (view) => {
    workspaceState.activeWorkspaceView = view;
  },
  setRuntimeTemplateRoute,
  setTaskRouteContextFromRoute,
  setView,
  showLibrary,
  showOperationsHome,
  workspaceRouteFor,
});
surfaceBridge.setNavigationShell(navigationShell);
bindApplicationEvents({
  callbacks: {
    clearSelection,
    closeBundlePanel,
    closeCommitForm,
    closeCustomSelects,
    closeDiff,
    closeLightbox,
    closeQuickNav,
    closeSettingsMenu,
    closeSidebar,
    closeTaskPanel,
    closeWorkBellPanel,
    confirmLeaveRuntimeDraft,
    createDocument,
    debounce,
    discardAllDrafts,
    discardDraft,
    gitPull,
    handleClipboardPaste,
    handleWorkspaceEntityModalKeydown,
    isSettingsMenuOpen,
    navigateCanonicalWorkspace,
    onFilterChange,
    openCommitForm,
    openDocMenu,
    openLintReport,
    openQuickNav,
    openSidebar,
    refreshDocuments,
    resizeDocumentTitle,
    saveAllDrafts,
    saveCurrentDocument,
    setDarkMode,
    setFiltersExpanded,
    setSidebarCollapsed,
    setTasksNavExpanded,
    showCreate,
    showLibrary,
    showWorkspaceSurface,
    storeDraft,
    submitCommitForm,
    syncSidebarShellState,
    syncTitleToMarkdown,
    toggleCurrentDocPin,
    toggleViewMode,
    updateQuickNavMatches,
    updateSaveState,
    workspaceHashPath,
  },
  documentRef: document,
  dom,
  navigationShell,
  notificationsShell,
  surfaceBridge,
  windowRef: window,
  workspaceState,
});





initializeAppShell({
  attachSidebarResize,
  enhanceSelect,
  filterSelects: [
    domainFilter,
    typeFilter,
    systemFilter,
    tagFilter,
    newDocType,
  ],
  loadDocuments,
  navigationShell,
  refreshChangesPanel,
  refreshGitStatus,
  refreshOperationsWorkSnapshot,
  restoreDarkMode,
  restoreSidebarCollapsed,
  restoreSidebarWidth,
  showLibrary,
  syncSidebarShellState,
  updateSaveState,
  windowRef: window,
});

// Title/path helpers for the new Home / Tasks / Docs IA.
// ---------- Quick create: ad-hoc task and workflow ----------

// Refresh "Saved · 2 min ago" every minute so the relative time stays current.
setInterval(() => {
  if (
    documentState.currentDoc &&
    editor.value === documentState.lastSavedContent
  ) {
    updateSaveState();
  }
}, 60000);
